# Generated by Django 3.1.3 on 2021-10-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211015_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consultation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consultation_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
