# Generated by Django 3.1.3 on 2021-10-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211015_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appointment_date',
            field=models.DateField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='consultation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
