# Generated by Django 3.1.3 on 2021-10-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211015_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test_result',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
